pipeline {
    agent {label 'lcrc'}
    stages {
        stage('PreTest') {
            steps {
	        script {
                  sh """echo 'Running PreTest...'
                  . /etc/profile
                  whoami
                  hostname
                  rm -f 'dashboards/jenkins.lcrc.anl.gov/nightly_log.txt'"""
                }
            }
	}
	stage('Make') {
	    steps {
		script {
		    sh """
                       . etc/profile
                       module load cmake
                       cd dashboards/jenkins.lcrc.anl.gov
                       bash do_cmake > test_log.txt
                       """
		}
	    }
	}
        stage('RunTest') {
            steps {
	        script {
                    sh """
                    . /etc/profile
                    module load cmake
		    cd dashboards/jenkins.lcrc.anl.gov
		    export LOG_FILE=nightly_log.txt
                    eval "env TEST_DIRECTORY=${env.workspace}/dashboards/jenkins.lcrc.anl.gov SCRIPT_DIRECTORY=${env.workspace}/dashboards/jenkins.lcrc.anl.gov ctest -VV -s ${env.workspace}/dashboards/jenkins.lcrc.anl.gov ctest_jenkins.cmake" >> test_log.txt
                    """
                }
            }
        }
    }
    post {
        always{
            archiveArtifacts 'dashboards/jenkins.lcrc.anl.gov/test_log.txt'
        }        
    }
	    
}
