pipeline {
    agent {label 'lcrc'}
    stages {
        stage('PreTest') {
            steps {
	        script {
                  sh """echo 'Running PreTest...'
                  set +x 
                  . /etc/profile 
                  set -x
                  whoami
                  hostname
                  rm -f 'dashboards/jenkins.lcrc.anl.gov/test_log.txt'"""
                }
            }
	}
	stage('Make') {
	    steps {
		script {
		    sh """
                       set +x 
                       . /etc/profile
                       module load cmake
                       set -x
                       cd dashboards/jenkins.lcrc.anl.gov
                       bash do-cmake > test_log.txt
                       """
		}
	    }
	}
        stage('RunTest') {
            steps {
	        script {
                    sh """
                    set +x
                    . /etc/profile
                    module load cmake
                    module load anaconda3/5.2.0
                    . /soft/anaconda3/5.2.0/etc/profile.d/conda.sh
                    set -x
                    conda activate
		    cd dashboards/jenkins.lcrc.anl.gov
                    eval "env TEST_DIRECTORY=${env.workspace}/dashboards/jenkins.lcrc.anl.gov SCRIPT_DIRECTORY=${env.workspace}/dashboards/jenkins.lcrc.anl.gov ctest -VV -s ${env.workspace}/dashboards/jenkins.lcrc.anl.gov ctest_jenkins.cmake" >> test_log.txt
                    """
                }
            }
        }
    }
    post {
        always{
            archiveArtifacts 'dashboards/jenkins.lcrc.anl.gov/test_log.txt'
        }        
    }
	    
}
