#!/bin/bash
#===============================
# Test script generated by CMake
#===============================
# Used for running swtc1
#===============================

NUM_CPUS=24

TEST_1="/home/jenkins/acme/scratch/HOMME_P24.f19_g16_rx1.A.melvin_gnu.C.jenkins_next_20170215_203221/bld/test_execs/swtcA/swtcA < /home/jenkins/slave/workspace/ACME_Basic_next/ACME_Climate/components/homme/test/reg_test/namelists/swtc1.nl"

NUM_TESTS=1


NC_OUTPUT_FILES="swtc11.nc "
NC_OUTPUT_REF=""
NC_OUTPUT_CHECKREF=""
TESTCASE_REF_TOL=""
