#!/usr/bin/env python

import sys, os
import subprocess
import re, socket
from time import asctime, strftime, localtime
from shutil import copy

print("Starting Setup")
print(os.getcwd())

# for flashTest - setup is successful if object/.success file exists in top level Flash/application directory 
# Create object directory if not exists and restart from scratch
print("Creating object dir")
if not os.path.exists("./object") :
    os.makedirs("./object")
print("Cleaning object dir")
subprocess.call(['bash' , '-c' , 'rm -rf ./object/*'])


    
# Path to src of application , top level dir includes Makefile 
# Can be replaced with command line argument  
 
if not os.path.exists("./src") :
    print("Missing application directory, create a symlink ln -s APP ./src")
elif not os.path.isfile("./src/Makefile") :
    print("Missing Makefile in ./src")
elif not os.path.exists("./test_input") :
    print("Missing test input directory ./test_input")          
# Create success file
else:
    print("Copying src into object directory")
    subprocess.call(['bash' , '-c' , 'cp -r ./src/* ./object'])
    print("Running make clean")
    subprocess.call(['bash' , '-c' , 'cd ./object/ && make clean'])
    print("Creating empty parameter file")
    subprocess.call(['bash' , '-c' , 'touch ./object/default.test.parameter'])
    print("Replacing Makefile (writing success file)")
    subprocess.call(['bash' , '-c' , 'cp Makefile ./object/'])
    subprocess.call(['bash' , '-c' , 'cp exeTest.sh ./object/'])
    subprocess.call(['bash' , '-c' , 'chmod a+x ./object/exeTest.sh'])
    subprocess.call(["touch", "object/.success"])
    print("Setup done")